version: '2'

networks:
  devnet:
    driver: bridge

services:
  nexus:
    image: sonatype/nexus
    container_name: nexus
    ports:
      - "8081:8081"
    networks:
      - devnet
    volumes:
      - "/opt/nexus/:/var/lib/nexus"

  jenkins:
    image: jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
    networks:
      - devnet
    volumes:
      - "$PWD/jenkins:/var/jenkins_home"
  
  sonarqube:
    image: sonarqube:6.3.1
    container_name: sonarqube
    restart: always
    ports:
    - "9000:9000"
    networks:
      - devnet
    depends_on:
      - sonardb
    links:
      - sonardb
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - "/opt/sonar/:/var/lib/sonar"

  sonardb:
    networks:
      - devnet
    image: postgres:9.6.1
    container_name: postgres
    restart: always
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
    - POSTGRESQL_DB=sonar
    ports:
      - "5432:5432"
    volumes:
      - "/opt/postgres:/var/lib/postgresql"

  cadvisor:
    image: google/cadvisor
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    ports:
    - "8090:8080"
    networks:
      - devnet
