apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      name: web
      labels:
        app: webapp
    spec:
      containers:
        - name: web
          image: devopsjuly22017/web:latest
          ports:
          - containerPort: 5000

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: web
#   labels:
#     app: webapp
# spec:
#  containers:
#   - name: web
#     image: devopsjuly22017/web:latest
#     ports:
#     - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: websvc
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
spec:
 containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
